name: statefile

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Is this project's memory real?
        uses: exodus611/statefile@main
        with:
          max-age-days: '14'
